---
##### Project-Wide Settings #####
# use_start_stop_scripts:     true # place per-enabled-app start/stop scripts in $HOME

##### Juice Shop #####
use_owasp_juiceshop:    true  # https://owasp.org/www-project-juice-shop/
# juiceshop_host_port:        '3000'

##### Yazuzlar Vulnerable Lab #####
# use_yavuzlar_vulnlab:   true # https://github.com/Yavuzlar/VulnLab
# vulnlab_host_port:      '3001'  

##### RailsGoat #####
# use_owasp_railsgoat:    true  # https://github.com/OWASP/railsgoat
# railsgoat_host_port:    '3002'

##### Damn Vulnerable Web Application #####
# use_dvwa:               true # https://github.com/digininja/DVWA
# dvwa_host_port:         '3003'

##### Damn Vulnerable GraphVL Application #####
# use_dvga:               true  # https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application
# dvga_host_port:         '3004'

##### NodeGoat #####
# use_owasp_nodegoat:     true # https://github.com/OWASP/NodeGoat
# nodegoat_host_port:     '3005'

##### SSRF Lab #####
# use_ssrf_lab:           true # https://github.com/incredibleindishell/SSRF_Vulnerable_Lab
# ssrf_lab_host_port:     '3006'

##### WebGoat #####
# use_webgoat:            true # https://github.com/WebGoat/WebGoat
# webgoat_host_webgoat_port:  '4080'
# webgoat_host_webwolf_port:  '4090'

##### Mutillidae #####
# use_mutillidae:         true # https://github.com/webpwnized/mutillidae
# mutillidae_host_port_dbadmin:     '5081'
# mutillidae_host_port_http:        '5080'
# mutillidae_host_port_https:       '5443'
# mutillidae_host_port_ldap:        '5389'
# mutillidae_host_port_ldap_admin:  '5082'

##### crAPI #####
# use_crAPI:              true # https://github.com/OWASP/crAPI
## NOTE: Refer to the crAPI README for port details. Ports are not customizeable due to nature of the app.

##### CI/CD Goat #####
## 🛑⚠️SECURITY WARNING🛑⚠️: unlike the other apps, this app binds to vulnerable services to 0.0.0.0
# use_cicdgoat:            true # https://github.com/cider-security-research/cicd-goat
## NOTE:  Refer to the CI/CD Goat README for port details. These ports are not customizeable due to the app's complexity and use of docker-in-docker.

##### VAmPI #####
# use_VAmPI:              true # https://github.com/erev0s/VAmPI
# VAmPI_host_port_secure: '6001'
# VAmPI_host_port_vuln:   '6002'

##### Damn Vulnerable Web Services #####
# use_dvws:               true # https://github.com/snoopysecurity/dvws-node
# dvws_host_port_http:      '7080'
# dvws_host_port_graphql:   '7081'
# dvws_host_port_xmlrpc:    '7090'

##### Security Shepherd #####
# use_shepherd:           true # https://github.com/OWASP/SecurityShepherd/
# shepherd_host_port_db:    '9306'
# shepherd_host_port_mongo: '9017'
# shepherd_host_port_http:  '9080'
# shepherd_host_port_https: '9443'
