---
##### Default Ports #####
#   - Strings (not integers)
#   - Override when calling the role to use a different port
#   - These are ports listening on the Docker host (need to be unique)
#   - Some apps use a single port, some use multiple ports

# Single-port apps: 3000 port range
juiceshop_host_port:    '3000'  
vulnlab_host_port:      '3001'  
railsgoat_host_port:    '3002'
dvwa_host_port:         '3003'
dvga_host_port:         '3004'
nodegoat_host_port:     '3005'
ssrf_lab_host_port:     '3006'

# Multi-port apps each get 1000 ports
## WebGoat: 4000 port range
webgoat_host_webgoat_port:  '4080'
webgoat_host_webwolf_port:  '4090'

## Mutillidae: 5000 port range
mutillidae_host_port_dbadmin:     '5081'
mutillidae_host_port_http:        '5080'
mutillidae_host_port_https:       '5443'
mutillidae_host_port_ldap:        '5389'
mutillidae_host_port_ldap_admin:  '5082'
#########################

## VAmPI: 6000 port range
VAmPI_host_port_secure: '6001'
VAmPI_host_port_vuln:   '6002'

##### App Configs #####
# OWASP Juice Shop: https://owasp.org/www-project-juice-shop/
use_owasp_juiceshop:    false
juiceshop_autostart:    false   # use_owasp_juiceshop must be true
juiceshop_image:        bkimminich/juice-shop # on docker hub
juiceshop_compose_file: "{{juiceshop_directory}}/compose.yaml"
juiceshop_directory:    "{{ansible_user_dir}}/juiceshop"

# VulnLab: https://github.com/Yavuzlar/VulnLab
use_yavuzlar_vulnlab:   false
vulnlab_autostart:      false   # use_yavuzlar_vulnlab must be true
vulnlab_image:          yavuzlar/vulnlab # on docker hub
vulnlab_directory:      "{{ansible_user_dir}}/vulnlab"
vulnlab_compose_file:   "{{ vulnlab_directory }}/compose.yaml"

# RailsGoat: https://github.com/OWASP/railsgoat
use_owasp_railsgoat:    false
railsgoat_autostart:    false   # use_owasp_railsgoat must be true
railsgoat_repo:         https://github.com/OWASP/railsgoat.git
railsgoat_directory:    "{{ansible_user_dir}}/railsgoat"
railsgoat_compose_file: "{{railsgoat_directory}}/compose.yaml"

# Damn Vulnerable Web Application (DVWA): https://github.com/digininja/DVWA
use_dvwa:               false
dvwa_autostart:         false   # use_dvwa must be true
dvwa_repo:              https://github.com/digininja/DVWA.git
dvwa_directory:         "{{ansible_user_dir}}/dvwa"
dvwa_compose_file:      "{{dvwa_directory}}/compose.yaml"

# Damn Vulnerable GraphQL Application (DVGA): https://github.com/dolevf/Damn-Vulnerable-GraphQL-Application
use_dvga:               false
dvga_autostart:         false   # use_dvga must be true
dvga_image:             dolevf/dvga # on docker hub
dvga_directory:         "{{ansible_user_dir}}/dvga"
dvga_compose_file:      "{{dvga_directory}}/compose.yaml"

# NodeGoat (https://github.com/OWASP/NodeGoat)
use_owasp_nodegoat:     false
nodegoat_autostart:     false   # use_owasp_nodegoat must be true
nodegoat_repo:          https://github.com/OWASP/NodeGoat.git
nodegoat_directory:     "{{ansible_user_dir}}/nodegoat"
nodegoat_compose_file:  "{{nodegoat_directory}}/compose.yaml"

# SSRF vulnerable Lab (https://github.com/incredibleindishell/SSRF_Vulnerable_Lab)
use_ssrf_lab:           false
ssrf_lab_autostart:     false   # use_ssrf_lab must be true
ssrf_lab_repo:          https://github.com/incredibleindishell/SSRF_Vulnerable_Lab.git
ssrf_lab_directory:     "{{ansible_user_dir}}/ssrf-lab"
ssrf_lab_compose_file:  "{{ssrf_lab_directory}}/compose.yaml"

# WebGoat (https://github.com/WebGoat/WebGoat)
use_webgoat:                false
webgoat_autostart:          false   # use_webgoat must be true
webgoat_image:              webgoat/webgoat # on docker hub
webgoat_directory:          "{{ansible_user_dir}}/webgoat"
webgoat_compose_file:       "{{webgoat_directory}}/compose.yaml"

# Mutillidae (https://github.com/webpwnized/mutillidae)
use_mutillidae:                   false
mutillidae_autostart:             false # use_mutillidae must be true
mutillidae_repo:                  https://github.com/webpwnized/mutillidae-docker.git
mutillidae_directory:             "{{ansible_user_dir}}/mutillidae"
mutillidae_compose_file:          "{{mutillidae_directory}}/compose.yaml"

# crAPI (https://github.com/OWASP/crAPI)
use_crAPI:                false
crAPI_autostart:          false   # use_crAPI must be true
crAPI_repo:               https://github.com/OWASP/crAPI.git
crAPI_directory:          "{{ansible_user_dir}}/crAPI"
crAPI_compose_file:       "{{crAPI_directory}}/deploy/docker/docker-compose.yml"

# CI/CD Goat (https://github.com/cider-security-research/cicd-goat)
# Using the default ports/containers, no customization.
use_cicdgoat:           false
cicdgoat_autostart:     false # use_cicdgoat must be true
cicdgoat_compose_url:   https://raw.githubusercontent.com/cider-security-research/cicd-goat/main/docker-compose.yaml
cicdgoat_directory:     "{{ansible_user_dir}}/cicd-goat"
cicdgoat_compose_file:  "{{cicdgoat_directory}}/compose.yaml"

# VAmPI (https://github.com/erev0s/VAmPI.git)
use_VAmPI:              false
VAmPI_repo:             https://github.com/erev0s/VAmPI.git
VAmPI_autostart:        false # use_VAmPI must be true
VAmPI_directory:        "{{ansible_user_dir}}/VAmPI"
VAmPI_compose_file:     "{{VAmPI_directory}}/compose.yaml"
