# This playbook sets up vulnlab prereqs:
#   - Prepares Kali for provisioning
#   - Installs OWASP ZAP
#   - Install Docker and Docker Compose

- name: Prepare Kali for provisioning
  hosts: all
  roles:
    - kali-customizations
  vars:
    - install_owasp_zap:    true

- name: Install Docker + Docker Compose
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
  vars:
    - docker_edition: 'ce'
    - docker_users: [vagrant]
    - docker_install_compose: true
    - docker_compose_version: 'v2.28.1'
    - docker_apt_gpg_key: 'https://download.docker.com/linux/debian/gpg'
    - docker_apt_repository: "deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
