# This playbook sets up vulnlab prereqs:
#   - Prepare Kali
#   - Install Docker and Docker Compose

- name: Prepare Kali for provisioning
  hosts: all
  tasks:
    - name: Install Python 3 libapt interface (needed for apt module)
      become: true
      apt:
        update_cache: yes
        state: latest
        pkg:
          - python3-apt
    - name: Add vagrant user to groups (enable shared folders, network management)
      become: true
      user:
        name: vagrant
        state: present
        groups:
          - vboxsf
          - netdev

- name: Install Docker + Docker Compose
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
  vars:
    - docker_edition: 'ce'
    - docker_users: [vagrant]
    - docker_install_compose_plugin: true
    - docker_compose_package: "docker-compose-plugin"
    - docker_compose_package_state: "present"
    - docker_apt_gpg_key: 'https://download.docker.com/linux/debian/gpg'
    - docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/debian bookworm {{ docker_apt_release_channel }}"
